### PR TITLE
code sprint info updates

### PR DESCRIPTION
**Pull request by davisc**
Code sprint accommodation updates for New Orleans and also added a new section to include the Boundless and Ithaca logos.

### CODE REVIEW

**Comment by garnertb** [comment]
The logos are looking a little sketchy:

screen shot 2015-11-05 at 2 33 31 pm

**Comment by garnertb** [comment]
FYI- I fixed the travis build and restarted this check.

**Comment by davisc** [comment]
@garnertb thanks. I updated the PR to address the section layout oddities.

**Comment by garnertb** [comment]
Merged in 7302357316126015187773323b6a93f94d8025a4.

**Pull request closed without merging**
