### PR TITLE
release 3.0

### PR DESCRIPTION
**Pull request by t-book**
@afabiani 

I've created a new RTD version from latest tag 3.0. Further changed geonode.org files to point to this new release. Last but not least I've created a new blog post which I'm attaching here for your convenience.  Hope I did not forget something ...

[screencapture-127-0-0-1-4000-blog-2020-05-18-geonode-3-2020-2020-05-18-13_59_41.pdf](https://github.com/GeoNode/geonode.github.com/files/4643964/screencapture-127-0-0-1-4000-blog-2020-05-18-geonode-3-2020-2020-05-18-13_59_41.pdf)

### CODE REVIEW

**Comment by giohappy** [comment]
Thanks @t-book .
Actually there are so many news for GN 3.0. 

Some that come to my mind:
- Python upgrade
- Django upgrade
- drop of GeoExt, with MapStore client as the new official one
- B/R refactoring with new features that make it able to be used for syncing instances (see docs)
- Read-Only and Mantenance modes
- GeoLimits

**Comment by t-book** [comment]
@giohappy thanks. I'm happy to change the post with your input. maybe let's wait a bit for more comments.

**Comment by afabiani** [comment]
@t-book awesome
Here below the full list of the main new features on GeoNode 3.0

- Python upgrade 3.7+
- Django upgrade 2.2.12
- GeoServer upgrade 2.16.2
- Moved Documentation to dedicated repository and build
- Integration of MapStore as new map viewer/composer
- Drop of GeoExt, with MapStore client as the new official one
- Local analytics/monitoring extension (https://docs.geonode.org/en/master/intermediate/monitoring/geonode_monitoring/index.html#analytics)
- Support for centralized analytics dashboard (https://docs.geonode.org/en/master/advanced/contrib/index.html#geonode-logstash-for-centralized-monitoring-analytics)
- Improvements to frontend for low-bandwidth environments (https://docs.geonode.org/en/master/basic/settings/index.html#cache-busting-media-enabled / https://github.com/GeoNode/geonode/issues?q=is%3Aissue+is%3Aclosed+label%3Aperformance)
- B/R refactoring with new features that make it able to be used for syncing instances (https://docs.geonode.org/en/master/intermediate/backup/index.html)
- Read-Only and Mantenance modes (https://docs.geonode.org/en/master/intermediate/modes/index.html)
- GeoLimits (https://docs.geonode.org/en/master/basic/permissions/index.html#geo-limits-permissions)
- Added "DOI" field to base metadata
- Extend resource search api with abstract and purpose fields (https://github.com/GeoNode/geonode/issues/5912)
- Improved Remote Services and Metadata Fetch
- Improved Message Inbox and Messaging & Norification System (https://github.com/GeoNode/geonode/issues/5914)
- Improved Thumbnails and Thumbnails Upload / edit before posting
- Improved Managemend Command (https://docs.geonode.org/en/master/admin/index.html#geonode-management-commands)

**Comment by afabiani** [comment]
I have updated the release changelog too
https://github.com/GeoNode/geonode/releases/tag/3.0

Also Pypi page here
https://pypi.org/project/GeoNode/3.0.0/

**Comment by t-book** [comment]
Great @afabiani your list has been really helpful. I've updated the post a bit. 

[screencapture-127-0-0-1-4000-blog-2020-05-18-geonode-3-2020-2020-05-19-11_43_28.pdf](https://github.com/GeoNode/geonode.github.com/files/4649549/screencapture-127-0-0-1-4000-blog-2020-05-18-geonode-3-2020-2020-05-19-11_43_28.pdf)

**Comment by afabiani** [comment]
Thanks @t-book awesome

**Pull request merged**
